#pragma once

enum SortType
{
    BATTING_AVERAGE = 1, STRIKE_RATE, SIX_AND_FOURS, SIX_AND_FOURS_WITH_STRIKERATE, BAT_AVG_WITH_STRIKERATE, 
    BAT_RUN_WITH_AVG,  BOWLING_AVG, BOWL_STRIKERATE, ECONOMY, FIVEWKT_FOURWKT_STRIKERATE, BOWL_AVG_WITH_STRIKERATE,
    BOWL_WKTS_WITH_AVG, BATTING_BOWLING_AVERAGE, MOST_RUNS_AND_WKTS, MAX_100_WITH_BAT_AVG, ZERO_100_50_WITH_AVG
};